/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mockup;

/**
 *
 * @author Ken
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UNHCRButton = new javax.swing.JButton();
        JHCOButton = new javax.swing.JButton();
        JGButton = new javax.swing.JButton();
        WPFButton = new javax.swing.JButton();
        WHOButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to ZARECIS Information Systems ");

        UNHCRButton.setText("UNHCR");
        UNHCRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNHCRButtonActionPerformed(evt);
            }
        });

        JHCOButton.setText("JHCO");
        JHCOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHCOButtonActionPerformed(evt);
            }
        });

        JGButton.setText("Jordanian Government");
        JGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JGButtonActionPerformed(evt);
            }
        });

        WPFButton.setText("WFP");
        WPFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WPFButtonActionPerformed(evt);
            }
        });

        WHOButton.setText("WHO");
        WHOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WHOButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Please Login to a Service Below");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UNHCRButton)
                        .addGap(45, 45, 45)
                        .addComponent(JHCOButton)
                        .addGap(49, 49, 49)
                        .addComponent(JGButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(WPFButton)
                .addGap(60, 60, 60)
                .addComponent(WHOButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UNHCRButton)
                    .addComponent(JHCOButton)
                    .addComponent(JGButton)
                    .addComponent(WPFButton)
                    .addComponent(WHOButton))
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UNHCRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNHCRButtonActionPerformed
        // TODO add your handling code here:
        UNHCRGUI unhcr = new UNHCRGUI();
    }//GEN-LAST:event_UNHCRButtonActionPerformed

    private void JGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JGButtonActionPerformed
        // TODO add your handling code here:
        JGGUI jg = new JGGUI();
    }//GEN-LAST:event_JGButtonActionPerformed

    private void JHCOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHCOButtonActionPerformed
        // TODO add your handling code here:
        JHCOGUI jhco = new JHCOGUI();
    }//GEN-LAST:event_JHCOButtonActionPerformed

    private void WPFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WPFButtonActionPerformed
        // TODO add your handling code here:
        WFPGUI wpf = new WFPGUI();
    }//GEN-LAST:event_WPFButtonActionPerformed

    private void WHOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WHOButtonActionPerformed
        // TODO add your handling code here:
        WHOGUI who = new WHOGUI();
    }//GEN-LAST:event_WHOButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JGButton;
    private javax.swing.JButton JHCOButton;
    private javax.swing.JButton UNHCRButton;
    private javax.swing.JButton WHOButton;
    private javax.swing.JButton WPFButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
